### ISSUE TITLE
wanna how to change the framesize or any commands like kunits?

### ISSUE THREAD

**Issue by ahrimanlol** [CruelDrool/Nurfed#2]

**Comment by CruelDrool** [comment]
Unlock the UI -> Mouse over a frame -> resize it with your scroll button (scroll up to enlarge, down to shrink.)

 Ctrl+shift+scroll up/down to reset.

**Comment by ahrimanlol** [comment]
amazing! thanks! as a cnwower,i changed the font to suit for cnwow,  can i share this link for free and of course i will indicate the author from u.
